export const BingoData = [
  { id: 1, text: "Steve" },
  { id: 2, text: "Someone who isn't called Harvey get's called Harvey" },
  { id: 3, text: "Screaming child in the background" },
  { id: 4, text: "That's it from me" },
  { id: 5, text: "Echo" },
  { id: 6, text: "Someone's mic doesn't work" },
  { id: 7, text: "Someone's mic doesn't work when they get looped back to" },
  { id: 8, text: "Someone without tasks updated" },
  { id: 9, text: "Trend line is going up" },
  { id: 10, text: "Someone new joins the stand-up" },
  { id: 11, text: "Someone is too quiet to hear" },
  { id: 12, text: "Harvey understands an unintelligible update" },
  { id: 13, text: 'Awkward silence after "Anything Else"' },
  { id: 14, text: "Okay Brilliant Thank You" },
  { id: 15, text: "Ade and Amira give the same update " },
  { id: 16, text: "That's it from a BA side" },
  { id: 17, text: "Someone is forgotten by the stand-up runner" },
  { id: 18, text: "Someone's completely unprepared for giving their update" },
  { id: 19, text: "Zoom name mishap" },
  { id: 20, text: "Someone speaks impossibly fast" },
  { id: 21, text: "Harvey's Bye" },
  { id: 22, text: "Chorus of goodbye at the end of stand-up" },
  { id: 23, text: "No one says goodbye at the end of stand-up" },
  { id: 24, text: "Pet appears" },
  { id: 25, text: "Abi absolutely loses it" },
];
