import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import { BingoData } from "../data";

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}
export default function Home() {
  const [shuffledData, setShuffledData] = useState();
  //const shuffledData = useMemo(() => shuffleArray(BingoData), [BingoData]);
  // let shuffledData;

  useEffect(() => {
    const tempData = shuffleArray(BingoData);
    const coorData = tempData.map((tempValue, index) => {
      return { coords: index, ...tempValue };
    });
    setShuffledData(coorData);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Stand-Up Bingo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Stand-Up Bingo</h1>

        <div className={styles.grid}>
          {shuffledData &&
            shuffledData.map((cardData) => {
              return <Card text={cardData.text}></Card>;
            })}
        </div>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
